version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"          # Terraform to install
    TG_VERSION: "0.67.6"         # Terragrunt to install
    TG_PARALLELISM: "8"          # Optional: run-all parallelism
    MODULES_DIR: "modules/v1"    # Read by terragrunt.hcl (coalesce(get_env("MODULES_DIR"), ...))

phases:
  install:
    commands:
      - set -euo pipefail
      - echo "[INSTALL] Installing jq and unzip"
      - yum -y install jq unzip >/dev/null
      - |
        echo "[INSTALL] Terraform ${TF_VERSION}"
        curl -fsSL -o /tmp/tf.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
        unzip -o /tmp/tf.zip -d /usr/local/bin >/dev/null
        terraform -version
      - |
        echo "[INSTALL] Terragrunt ${TG_VERSION}"
        curl -fsSL -o /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64"
        chmod +x /usr/local/bin/terragrunt
        terragrunt -version

  pre_build:
    commands:
      - set -euo pipefail
      - echo "[PRE] Resolve latest intake folder"
      - cd "$CODEBUILD_SRC_DIR"
      - |
        if [[ -n "${INTAKE_DIR:-}" && -d "${INTAKE_DIR}" ]]; then
          sel="${INTAKE_DIR}"
        else
          sel="$(find live/sandbox -maxdepth 1 -type d -name 'intake_id_*' 2>/dev/null | sort -V | tail -n1 || true)"
        fi
        if [[ -z "$sel" || ! -d "$sel" ]]; then
          echo "[PRE] No intake dir; writing NOOP and exiting 0"
          mkdir -p build-status && printf '{"status":"noop","reason":"no_intake_dir"}' > build-status/result.json
          exit 0
        fi
        export INTAKE_DIR="$sel"; echo "[PRE] INTAKE_DIR=$INTAKE_DIR"

      - |
        JSON_PATH="${INTAKE_DIR}/inputs.json"
        if [[ ! -f "$JSON_PATH" ]]; then
          echo "[PRE] inputs.json missing; NOOP"
          mkdir -p build-status && printf '{"status":"noop","reason":"no_inputs_json"}' > build-status/result.json
          exit 0
        fi
        cat "$JSON_PATH" | jq .
        export AWS_DEFAULT_REGION="$(jq -r '.region // .aws_region // "us-east-1"' "$JSON_PATH")"
        echo "[PRE] Region -> $AWS_DEFAULT_REGION"

      - |
        ROLE_ARN="$(jq -r '.assume_role_arn // .iam_role // empty' "$JSON_PATH")"
        if [[ -n "$ROLE_ARN" && "$ROLE_ARN" != "null" ]]; then
          echo "[PRE] Assuming role: $ROLE_ARN"
          CREDS_JSON="$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name tg-${CODEBUILD_BUILD_ID##*:} --duration-seconds 3600)"
          export AWS_ACCESS_KEY_ID="$(jq -r '.Credentials.AccessKeyId'    <<< "$CREDS_JSON")"
          export AWS_SECRET_ACCESS_KEY="$(jq -r '.Credentials.SecretAccessKey' <<< "$CREDS_JSON")"
          export AWS_SESSION_TOKEN="$(jq -r '.Credentials.SessionToken'   <<< "$CREDS_JSON")"
          aws sts get-caller-identity --query Arn --output text
        else
          echo "[PRE] No assume role; using CodeBuild credentials"
        fi

  build:
    commands:
      - set +e
      - cd "$INTAKE_DIR"
      - export TERRAGRUNT_NON_INTERACTIVE=true
      - TG_PAR_ARGS=( --terragrunt-parallelism "${TG_PARALLELISM}" )
      - EXCLUDES=( --terragrunt-exclude-dir versions --terragrunt-exclude-dir decommission )
      - echo "[BUILD] terragrunt init (best-effort)"; terragrunt run-all init -reconfigure "${TG_PAR_ARGS[@]}" || true
      - echo "[BUILD] terragrunt apply (excluding versions/ & decommission/)"
      - terragrunt run-all apply "${TG_PAR_ARGS[@]}" "${EXCLUDES[@]}" -auto-approve
      - APP_RC=$?
      - |
        DEC_PRESENT=false
        if [[ -d "decommission" ]] && find decommission -type f -name terragrunt.hcl -print -quit | grep -q . ; then
          DEC_PRESENT=true
        fi
        if [[ $APP_RC -ne 0 && "$DEC_PRESENT" == "true" ]]; then
          echo "[FALLBACK] Destroy decommission, then retry apply"
          ( cd decommission && terragrunt run-all init -reconfigure "${TG_PAR_ARGS[@]}" || true )
          ( cd decommission && terragrunt run-all destroy "${TG_PAR_ARGS[@]}" -auto-approve ) || true
          terragrunt run-all apply "${TG_PAR_ARGS[@]}" "${EXCLUDES[@]}" -auto-approve
          APP_RC=$?
        fi
      - |
        DEC_RC=0
        if [[ "$DEC_PRESENT" == "true" ]]; then
          echo "[BUILD] Final decommission pass"
          ( cd decommission && terragrunt run-all destroy "${TG_PAR_ARGS[@]}" -auto-approve ) || DEC_RC=$?
        else
          echo "[BUILD] No decommission folder; skipping"
        fi
      - echo "[BUILD] APP_RC=$APP_RC DEC_RC=$DEC_RC" ; echo "$APP_RC" >/tmp/app.rc ; echo "$DEC_RC" >/tmp/dec.rc

  post_build:
    commands:
      - |
        APP_RC="$(cat /tmp/app.rc 2>/dev/null || echo 0)"
        DEC_RC="$(cat /tmp/dec.rc 2>/dev/null || echo 0)"
        mkdir -p build-status
        STATUS=$([ "$APP_RC" -eq 0 ] && [ "$DEC_RC" -eq 0 ] && echo success || echo partial)
        printf '{"status":"%s","intake_dir":"%s","app_rc":%s,"dec_rc":%s}\n' "$STATUS" "${INTAKE_DIR:-}" "$APP_RC" "$DEC_RC" > build-status/result.json
        echo "[POST] Wrote build-status/result.json -> $STATUS"

artifacts:
  files:
    - build-status/result.json
  name: BuildArtifact
  discard-paths: yes
