version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    MODULES_DIR: "modules/v1"
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "[INFO] 🔧 Installing Terraform, Terragrunt and required utilities..."

      # Install unzip + jq if not present (handles both Amazon Linux / Ubuntu images)
      - |
        if ! command -v unzip >/dev/null 2>&1; then
          echo "[INFO] 📦 Installing unzip and jq..."
          if command -v yum >/dev/null 2>&1; then
            yum install -y unzip jq
          elif command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y unzip jq
          else
            echo "[WARN] ⚠️ Neither yum nor apt-get found. Skipping package install."
          fi
        else
          echo "[INFO] ✅ unzip already installed"
        fi

      # Install Terraform
      - |
        TERRAFORM_VERSION="1.9.8"
        echo "[INFO] 📥 Downloading Terraform v${TERRAFORM_VERSION}..."
        curl -sLo terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
        unzip -o terraform.zip
        mv terraform /usr/local/bin/terraform
        chmod +x /usr/local/bin/terraform
        rm -f terraform.zip
        echo "[INFO] ✅ Terraform installed at $(command -v terraform)"

      # Install Terragrunt
      - |
        TERRAGRUNT_VERSION="0.67.0"
        echo "[INFO] 📥 Downloading Terragrunt v${TERRAGRUNT_VERSION}..."
        curl -sLo /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64"
        chmod +x /usr/local/bin/terragrunt
        echo "[INFO] ✅ Terragrunt installed at $(command -v terragrunt)"

      # Verify dependencies
      - echo "[INFO] 🔧 Verifying dependencies......"
      - terraform --version
      - terragrunt --version
      - aws --version || echo "[WARN] ⚠️ aws CLI not found in PATH"
      - python --version
      - jq --version
      - git --version
      - curl --version

  pre_build:
    commands:
      - echo "[INFO] 🔍 Detecting latest intake in live/sandbox..."
      - cd live/sandbox || { echo "[ERROR] ❌ live/sandbox not found"; exit 1; }
      - echo "[DEBUG] Listing sandbox directory structure (top 50 lines):"
      - ls -R | head -50

      # Detect latest intake_id_XXX folder (all lowercase)
      - >
        INTAKE_ID=$(find . -maxdepth 1 -type d -printf '%f\n' | grep -E '^intake_id_' | sort -V | tail -n1) &&
        [ -n "$INTAKE_ID" ] || { echo "[ERROR] ❌ No intake_id_* directory found!"; exit 1; }
      - echo "[INFO] ✅ Detected latest intake directory:" $INTAKE_ID
      - export INTAKE_ID

      # Detect inputs.json
      - JSON_PATH="./$INTAKE_ID/inputs.json"
      - if [ ! -f "$JSON_PATH" ]; then
          echo "[ERROR] ❌ inputs.json not found at $JSON_PATH";
          echo "[DEBUG] Listing current folder content:";
          ls -R;
          exit 1;
        fi
      - echo "[INFO] ✅ Found inputs.json at $JSON_PATH"
      - cat "$JSON_PATH" | jq .
      - export AWS_ACCOUNT_ID=$(jq -r '.aws_account_id' "$JSON_PATH")
      - export IAM_ROLE=$(jq -r '.iam_role' "$JSON_PATH")
      - export REQUEST_ID=$(jq -r '.request_id' "$JSON_PATH")

      - if [ -z "$AWS_ACCOUNT_ID" ] || [ "$AWS_ACCOUNT_ID" == "null" ]; then
          echo "[ERROR] ❌ aws_account_id missing in inputs.json";
          exit 1;
        fi
      - if [ -z "$IAM_ROLE" ] || [ "$IAM_ROLE" == "null" ]; then
          echo "[ERROR] ❌ iam_role missing in inputs.json";
          exit 1;
        fi
      - echo "$IAM_ROLE"

  build:
    commands:
      - echo "$IAM_ROLE"
      - echo "[INFO] 🔧 Initializing Terragrunt for $INTAKE_ID..."
      - cd "./$INTAKE_ID"
      - terragrunt run-all init -reconfigure --terragrunt-non-interactive
      - echo "[INFO] 🚀 Running Terragrunt apply..."
      - terragrunt run-all apply -auto-approve --terragrunt-non-interactive
      - cd ../../../..
